name: Build and release debug APK

env:
  main_project_module: app
  app_name: Hulumula

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set current date as env variable
      run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    # - name: Build with Gradle
    #   run: ./gradlew build

    - name: Run gradle tests
      run: ./gradlew test

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # Noted For Output [main_project_module]/build/outputs/apk/debug/
    - name: Upload APK Debug - ${{ env.repository_name }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.date_today }} - ${{ env.app_name }} - APK(s) debug generated
        path: ${{ env.main_project_module }}/build/outputs/apk/debug/
